use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use crate::domain::package::{MigrationResult, PackageMigration};

/// User home directory. Hard-fails if `$HOME` is unset rather than degrading
/// to a world-writable fallback like `/tmp` — rollback scripts and Brewfiles
/// could otherwise be readable/writable by other users on shared systems.
pub(crate) fn home_dir() -> io::Result<PathBuf> {
    std::env::var_os("HOME")
        .map(PathBuf::from)
        .filter(|p| !p.as_os_str().is_empty())
        .ok_or_else(|| io::Error::other("$HOME is not set; refusing to use a fallback directory"))
}

/// Base directory for apt2brew data: ~/.apt2brew/
fn base_dir() -> io::Result<PathBuf> {
    Ok(home_dir()?.join(".apt2brew"))
}

/// Generate a Brewfile at ~/Brewfile with the migrated packages.
pub fn write_brewfile(packages: &[PackageMigration]) -> io::Result<PathBuf> {
    let path = home_dir()?.join("Brewfile");
    let mut content = String::from("# Generated by apt2brew\n\n");

    for pkg in packages.iter().filter(|p| p.is_selected) {
        if let Some(brew_name) = &pkg.brew_name {
            content.push_str(&format!("brew \"{brew_name}\"\n"));
        }
    }

    fs::write(&path, &content)?;
    Ok(path)
}

/// Reserve a rollback-script path in ~/.apt2brew/ for the current run.
///
/// Call this *before* any system modifications so incremental writes during
/// the migration have a stable target. The file is not created until
/// `write_rollback_script_at` is called.
pub fn rollback_script_path() -> io::Result<PathBuf> {
    let dir = base_dir()?;
    fs::create_dir_all(&dir)?;
    Ok(dir.join(format!("rollback-{}.sh", unique_timestamp())))
}

/// Write (or overwrite) a rollback script at `path` reflecting current results.
///
/// Designed to be called after every successful brew install so the on-disk
/// rollback always matches real system state. Honors the invariant documented
/// in CLAUDE.md: rollback is available before apt/snap removal runs.
pub fn write_rollback_script_at(path: &Path, results: &[MigrationResult]) -> io::Result<()> {
    let mut script = String::from("#!/bin/bash\n");
    script.push_str("# apt2brew rollback script\n");
    script.push_str(&format!("# Generated: {}\n", unique_timestamp()));
    script.push_str("# Run this script to undo the migration.\n\n");
    script.push_str("set -e\n\n");

    let successful: Vec<_> = results.iter().filter(|r| r.brew_installed).collect();

    if successful.is_empty() {
        script.push_str("echo 'Nothing to rollback.'\n");
    } else {
        script.push_str("echo 'Rolling back apt2brew migration...'\n\n");

        for r in &successful {
            let is_snap = r.source == crate::domain::package::PackageSource::Snap;
            let mgr = if is_snap { "snap" } else { "APT" };
            let install_cmd = if is_snap {
                format!("sudo snap install {}", r.package)
            } else {
                format!("sudo apt install -y {}", r.package)
            };

            script.push_str(&format!("# Rollback: {}\n", r.package));
            script.push_str(&format!("echo 'Reinstalling {} via {mgr}...'\n", r.package));
            script.push_str(&format!("{install_cmd}\n"));
            script.push_str(&format!(
                "echo 'Removing {} from Homebrew...'\n",
                r.brew_name
            ));
            script.push_str(&format!("brew uninstall {} || true\n\n", r.brew_name));
        }

        script.push_str("echo 'Rollback complete.'\n");
    }

    fs::write(path, &script)?;

    // Per-user executable script. 0700 keeps the package list private on
    // shared multi-user systems; the script is invoked by its owner only.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(path, fs::Permissions::from_mode(0o700))?;
    }

    Ok(())
}

/// Write a migration log entry.
pub fn write_log(results: &[MigrationResult]) -> io::Result<PathBuf> {
    let dir = base_dir()?.join("logs");
    fs::create_dir_all(&dir)?;

    let timestamp = unique_timestamp();
    let path = dir.join(format!("migration-{timestamp}.log"));

    let mut log = String::new();
    log.push_str(&format!("apt2brew migration log — {timestamp}\n"));
    log.push_str(&format!("{}\n\n", "=".repeat(50)));

    for r in results {
        let status = if r.error.is_some() {
            "FAILED"
        } else if r.apt_removed {
            "OK"
        } else {
            "PARTIAL"
        };
        log.push_str(&format!(
            "[{status}] {} -> brew:{}\n",
            r.package, r.brew_name
        ));
        log.push_str(&format!(
            "       brew_installed={} path_verified={} apt_removed={} was_already_installed={}\n",
            r.brew_installed, r.path_verified, r.apt_removed, r.was_already_installed
        ));
        if let Some(err) = &r.error {
            log.push_str(&format!("       error: {err}\n"));
        }
        log.push('\n');
    }

    let ok_count = results
        .iter()
        .filter(|r| r.error.is_none() && r.apt_removed)
        .count();
    let partial_count = results
        .iter()
        .filter(|r| r.error.is_none() && !r.apt_removed)
        .count();
    let fail_count = results.iter().filter(|r| r.error.is_some()).count();
    log.push_str(&format!(
        "Summary: {ok_count} succeeded, {partial_count} partial, {fail_count} failed\n",
    ));

    fs::write(&path, &log)?;
    Ok(path)
}

/// Print dry-run output showing what would happen.
pub fn print_dry_run(packages: &[PackageMigration]) {
    let selected: Vec<_> = packages.iter().filter(|p| p.is_selected).collect();

    println!("\n  DRY RUN — no changes will be made\n");
    println!(
        "  The following {} packages would be migrated:\n",
        selected.len()
    );

    for pkg in &selected {
        let brew = pkg.brew_name.as_deref().unwrap_or("?");
        println!("    brew install {brew:<24}  (replaces apt:{0})", pkg.name);
    }

    println!("\n  To execute, run: apt2brew migrate --execute\n");
}

/// Print migration results summary.
pub fn print_results(results: &[MigrationResult], rollback_path: &Path, log_path: &Path) {
    println!("\n  Migration Results\n");

    for r in results {
        let (icon, suffix) = if r.error.is_some() {
            ("!!", "")
        } else if r.apt_removed {
            if r.was_already_installed {
                ("OK", " (brew copy was pre-existing — not refreshed)")
            } else {
                ("OK", "")
            }
        } else if r.was_already_installed {
            (
                "~~",
                " (already in brew, source not removed — nothing to do)",
            )
        } else {
            ("~~", " (brew installed, source not removed)")
        };
        println!("  [{icon}] {} -> brew:{}{suffix}", r.package, r.brew_name);
        if let Some(err) = &r.error {
            println!("       {err}");
        }
    }

    let ok_count = results
        .iter()
        .filter(|r| r.error.is_none() && r.apt_removed)
        .count();
    let partial_count = results
        .iter()
        .filter(|r| r.error.is_none() && !r.apt_removed)
        .count();
    let fail_count = results.iter().filter(|r| r.error.is_some()).count();

    print!("\n  {ok_count} succeeded");
    if partial_count > 0 {
        print!(", {partial_count} partial (source not removed)");
    }
    if fail_count > 0 {
        print!(", {fail_count} failed");
    }
    println!();
    println!("  Rollback script: {}", rollback_path.display());
    println!("  Log: {}\n", log_path.display());
}

/// `<unix_seconds>-<nanos>-<pid>` — unique per-call so two runs in the same
/// second (or two concurrent runs) cannot truncate each other's rollback file.
fn unique_timestamp() -> String {
    let duration = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default();
    format!(
        "{}-{:09}-{}",
        duration.as_secs(),
        duration.subsec_nanos(),
        std::process::id()
    )
}
