use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use crate::domain::package::{MigrationResult, PackageMigration};

/// Base directory for apt2brew data: ~/.apt2brew/
fn base_dir() -> PathBuf {
    dirs_path().join(".apt2brew")
}

fn dirs_path() -> PathBuf {
    std::env::var("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("/tmp"))
}

/// Generate a Brewfile at ~/Brewfile with the migrated packages.
pub fn write_brewfile(packages: &[PackageMigration]) -> io::Result<PathBuf> {
    let path = dirs_path().join("Brewfile");
    let mut content = String::from("# Generated by apt2brew\n\n");

    for pkg in packages.iter().filter(|p| p.is_selected) {
        if let Some(brew_name) = &pkg.brew_name {
            content.push_str(&format!("brew \"{brew_name}\"\n"));
        }
    }

    fs::write(&path, &content)?;
    Ok(path)
}

/// Generate a rollback script that reinstalls packages via APT and removes them from brew.
pub fn write_rollback_script(results: &[MigrationResult]) -> io::Result<PathBuf> {
    let dir = base_dir();
    fs::create_dir_all(&dir)?;

    let timestamp = chrono_timestamp();
    let path = dir.join(format!("rollback-{timestamp}.sh"));

    let mut script = String::from("#!/bin/bash\n");
    script.push_str("# apt2brew rollback script\n");
    script.push_str(&format!("# Generated: {timestamp}\n"));
    script.push_str("# Run this script to undo the migration.\n\n");
    script.push_str("set -e\n\n");

    let successful: Vec<_> = results.iter().filter(|r| r.brew_installed).collect();

    if successful.is_empty() {
        script.push_str("echo 'Nothing to rollback.'\n");
    } else {
        script.push_str("echo 'Rolling back apt2brew migration...'\n\n");

        for r in &successful {
            script.push_str(&format!("# Rollback: {}\n", r.package));
            script.push_str(&format!("echo 'Reinstalling {} via APT...'\n", r.package));
            script.push_str(&format!("sudo apt install -y {}\n", r.package));
            script.push_str(&format!(
                "echo 'Removing {} from Homebrew...'\n",
                r.brew_name
            ));
            script.push_str(&format!("brew uninstall {} || true\n\n", r.brew_name));
        }

        script.push_str("echo 'Rollback complete.'\n");
    }

    fs::write(&path, &script)?;

    // Make executable
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&path, fs::Permissions::from_mode(0o755))?;
    }

    Ok(path)
}

/// Write a migration log entry.
pub fn write_log(results: &[MigrationResult]) -> io::Result<PathBuf> {
    let dir = base_dir().join("logs");
    fs::create_dir_all(&dir)?;

    let timestamp = chrono_timestamp();
    let path = dir.join(format!("migration-{timestamp}.log"));

    let mut log = String::new();
    log.push_str(&format!("apt2brew migration log — {timestamp}\n"));
    log.push_str(&format!("{}\n\n", "=".repeat(50)));

    for r in results {
        let status = if r.error.is_none() { "OK" } else { "FAILED" };
        log.push_str(&format!(
            "[{status}] {} -> brew:{}\n",
            r.package, r.brew_name
        ));
        log.push_str(&format!(
            "       brew_installed={} path_verified={} apt_removed={}\n",
            r.brew_installed, r.path_verified, r.apt_removed
        ));
        if let Some(err) = &r.error {
            log.push_str(&format!("       error: {err}\n"));
        }
        log.push('\n');
    }

    let ok_count = results.iter().filter(|r| r.error.is_none()).count();
    let fail_count = results.len() - ok_count;
    log.push_str(&format!(
        "Summary: {} succeeded, {} failed\n",
        ok_count, fail_count
    ));

    fs::write(&path, &log)?;
    Ok(path)
}

/// Print dry-run output showing what would happen.
pub fn print_dry_run(packages: &[PackageMigration]) {
    let selected: Vec<_> = packages.iter().filter(|p| p.is_selected).collect();

    println!("\n  DRY RUN — no changes will be made\n");
    println!(
        "  The following {} packages would be migrated:\n",
        selected.len()
    );

    for pkg in &selected {
        let brew = pkg.brew_name.as_deref().unwrap_or("?");
        println!("    brew install {brew:<24}  (replaces apt:{0})", pkg.name);
    }

    println!("\n  To execute, run: apt2brew migrate --execute\n");
}

/// Print migration results summary.
pub fn print_results(results: &[MigrationResult], rollback_path: &Path, log_path: &Path) {
    println!("\n  Migration Results\n");

    for r in results {
        let icon = if r.error.is_none() { "OK" } else { "!!" };
        println!("  [{icon}] {} -> brew:{}", r.package, r.brew_name);
        if let Some(err) = &r.error {
            println!("       {err}");
        }
    }

    let ok_count = results.iter().filter(|r| r.error.is_none()).count();
    let fail_count = results.len() - ok_count;

    println!("\n  {} succeeded, {} failed", ok_count, fail_count);
    println!("  Rollback script: {}", rollback_path.display());
    println!("  Log: {}\n", log_path.display());
}

fn chrono_timestamp() -> String {
    // Simple timestamp without chrono dependency
    let duration = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default();
    format!("{}", duration.as_secs())
}
